import type { BuilderDeployment, BuilderRelease, BuilderVerification, SessionPayload } from "./model";
export const projectId = "builder/project:exact";
export const sessionId = `app_build_${"a".repeat(48)}`;
export const checkpointId = `app_build_checkpoint_${"b".repeat(48)}`;
export const verificationId = `app_build_verification_${"c".repeat(48)}`;
export const deploymentId = `app_build_deployment_${"d".repeat(48)}`;
export const releaseId = `app_build_release_${"e".repeat(48)}`;
export const stamp = "2026-10-04T00:00:00.000Z";
export const digest = "f".repeat(64);
export const browserEvidence = { status: "retired" as const, captures: [], legacyField: true as const, summary: "Legacy captures are retired.", replacement: { mode: "deterministic" as const, version: 1 as const, phase: "checkpoint" as const, status: "passed" as const, summary: "Lint and typecheck passed.", signals: [{ name: "lint" as const, status: "passed" as const }, { name: "typecheck" as const, status: "passed" as const }] } };
export function verification(): BuilderVerification { return { id: verificationId, sessionId, checkpointId, workspaceSha256: digest, status: "passed", checks: [{ command: "lint", status: "passed", exitCode: 0, durationMs: 2, outputSha256: digest }, { command: "typecheck", status: "passed", exitCode: 0, durationMs: 2, outputSha256: digest }], browserEvidence, createdAt: stamp }; }
export function deployment(): BuilderDeployment { return { id: deploymentId, checkpointId, verificationId, workspaceSha256: digest, fileManifestSha256: digest, fileCount: 1, byteCount: 18, secretScanSha256: digest, smokeRoutes: ["/"], providerDeploymentId: "provider:exact-preview", status: "ready", logs: { status: "captured", sha256: digest, eventCount: 2 }, routeEvidence: { status: "passed", routes: [{ path: "/", status: "passed", statusCode: 200, durationMs: 2 }] }, browserEvidence, createdAt: stamp, updatedAt: stamp }; }
export function release(): BuilderRelease { const preview = deployment(); return { id: releaseId, deploymentId, previewProviderDeploymentId: preview.providerDeploymentId!, workspaceSha256: digest, previewEvidenceSha256: digest, releaseDigest: digest, migrationEvidence: { status: "not_declared", fileCount: 0, manifestSha256: digest }, rollbackEvidence: { status: "available", providerDeploymentId: "provider:previous-production", deploymentUrl: "https://previous.example.test" }, status: "review_pending", logs: preview.logs, routeEvidence: preview.routeEvidence, browserEvidence, createdAt: stamp, updatedAt: stamp, expiresAt: "2026-10-04T00:15:00.000Z" }; }
export function snapshot(): SessionPayload { return { session: { id: sessionId, projectId, status: "ready", revision: 2, currentCheckpointId: checkpointId, templateId: "starter", updatedAt: stamp }, activity: [{ id: "activity:1", eventType: "app_builder.sentinel.reviewed", detail: { verificationId, checkpointId, workspaceSha256: digest, verdict: "passed" }, occurredAt: stamp }], checkpoints: [{ id: checkpointId, sessionId, workspaceSha256: digest, fileCount: 1, snapshotBytes: 18, reason: "manual", label: "Exact sealed source", sessionRevision: 2, createdAt: stamp }], verifications: [verification()], deliveries: [], deployments: [deployment()], releases: [release()], repositoryBinding: null, repositoryWorkspace: null, github: { configured: true, missing: [] }, vercel: { configured: true, missing: [] }, previewUrl: "https://sandbox.example.test/?asael_preview=private-token" }; }
