export type ConnectionCatalogItem = {
  id: string;
  name: string;
  category: "code" | "communication" | "knowledge" | "data" | "automation" | "browser";
  adapter: "mcp" | "openapi" | "native";
  status: "ready" | "requires_credentials" | "planned";
  baseUrl?: string;
  endpoint?: string;
  authEnvVars: string[];
  authHeaderName?: string;
  capabilities: string[];
  riskLevel: 0 | 1 | 2 | 3;
  approvalRequired: boolean;
};

export const connectionCatalog: ConnectionCatalogItem[] = [
  {
    id: "github",
    name: "GitHub",
    category: "code",
    adapter: "openapi",
    status: "requires_credentials",
    baseUrl: "https://api.github.com",
    authEnvVars: ["GITHUB_TOKEN"],
    authHeaderName: "authorization",
    capabilities: ["repositories", "issues", "pull requests", "workflow dispatch"],
    riskLevel: 2,
    approvalRequired: true,
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "communication",
    adapter: "native",
    status: "ready",
    baseUrl: "https://gmail.googleapis.com",
    authEnvVars: ["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"],
    capabilities: ["recent message metadata", "incremental sync", "knowledge ingestion"],
    riskLevel: 0,
    approvalRequired: false,
  },
  {
    id: "slack",
    name: "Slack",
    category: "communication",
    adapter: "openapi",
    status: "requires_credentials",
    baseUrl: "https://slack.com/api",
    authEnvVars: ["SLACK_BOT_TOKEN"],
    authHeaderName: "authorization",
    capabilities: ["messages", "channels", "threads", "workspace events"],
    riskLevel: 2,
    approvalRequired: true,
  },
  {
    id: "notion",
    name: "Notion",
    category: "knowledge",
    adapter: "openapi",
    status: "requires_credentials",
    baseUrl: "https://api.notion.com/v1",
    authEnvVars: ["NOTION_TOKEN"],
    authHeaderName: "authorization",
    capabilities: ["pages", "databases", "comments", "workspace search"],
    riskLevel: 2,
    approvalRequired: true,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "knowledge",
    adapter: "native",
    status: "ready",
    baseUrl: "https://www.googleapis.com/drive/v3",
    authEnvVars: ["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"],
    capabilities: ["recent files", "document export", "incremental sync", "knowledge ingestion"],
    riskLevel: 0,
    approvalRequired: false,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "automation",
    adapter: "native",
    status: "ready",
    baseUrl: "https://www.googleapis.com/calendar/v3",
    authEnvVars: ["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"],
    capabilities: ["calendar events", "incremental sync", "knowledge ingestion"],
    riskLevel: 0,
    approvalRequired: false,
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "data",
    adapter: "openapi",
    status: "requires_credentials",
    baseUrl: "https://YOUR_PROJECT_REF.supabase.co",
    authEnvVars: ["SUPABASE_SERVICE_ROLE_KEY"],
    authHeaderName: "apikey",
    capabilities: ["PostgREST", "storage", "edge functions", "auth admin"],
    riskLevel: 3,
    approvalRequired: true,
  },
  {
    id: "neon",
    name: "Neon",
    category: "data",
    adapter: "openapi",
    status: "requires_credentials",
    baseUrl: "https://console.neon.tech/api/v2",
    authEnvVars: ["NEON_API_KEY"],
    authHeaderName: "authorization",
    capabilities: ["projects", "branches", "databases", "connection strings"],
    riskLevel: 2,
    approvalRequired: true,
  },
  {
    id: "upstash",
    name: "Upstash",
    category: "data",
    adapter: "openapi",
    status: "requires_credentials",
    baseUrl: "https://api.upstash.com/v2",
    authEnvVars: ["UPSTASH_API_KEY"],
    authHeaderName: "authorization",
    capabilities: ["Redis", "Vector", "QStash", "Kafka"],
    riskLevel: 2,
    approvalRequired: true,
  },
  {
    id: "browser-automation",
    name: "Browser Automation",
    category: "browser",
    adapter: "mcp",
    status: "requires_credentials",
    endpoint: "https://your-browser-mcp.example.com/mcp",
    authEnvVars: ["BROWSER_MCP_TOKEN"],
    capabilities: ["navigate", "click", "type", "screenshot", "extract"],
    riskLevel: 2,
    approvalRequired: true,
  },
  {
    id: "custom-mcp",
    name: "Custom MCP Server",
    category: "automation",
    adapter: "mcp",
    status: "ready",
    endpoint: "https://example.com/mcp",
    authEnvVars: ["CUSTOM_MCP_BEARER_TOKEN"],
    capabilities: ["discover tools", "schema execution", "governed audit"],
    riskLevel: 2,
    approvalRequired: true,
  },
  {
    id: "webhook-trigger",
    name: "Webhook Trigger",
    category: "automation",
    adapter: "native",
    status: "ready",
    authEnvVars: ["OMNIAGENT_WEBHOOK_SECRET"],
    capabilities: ["signed event intake", "workflow run creation", "queue enqueue", "trigger audit"],
    riskLevel: 1,
    approvalRequired: false,
  },
];
