import 'dart:convert';
import 'dart:io';

import 'package:asael/features/integrations/connector_contracts.dart';
import 'package:asael/features/integrations/connector_mcp_registration_contracts.dart';
import 'package:flutter_test/flutter_test.dart';

import 'connector_mcp_registration_fixtures.dart';
import 'connector_fixtures.dart';

void main() {
  // Independent TypeScript exports were parsed/resealed by the server schemas;
  // their domain hashes are never regenerated by the Dart fixture builders.
  final server = connectorMap(
    jsonDecode(
      File('test/fixtures/connector_mcp_registration/server.json')
          .readAsStringSync(),
    ),
  );
  for (final name in [
    'noneClean',
    'nonePrivate',
    'envClean',
    'envPrivate',
    'vaultClean',
    'vaultPrivate',
  ]) {
    test(
      'TypeScript $name preparation, abandonment and registration retain exact Dart identity and hashes',
      () async {
        final fixture = connectorMap(server[name]),
            scope = connectorMap(fixture['scope']);
        final owner = ConnectorOwner(
          tenantId: scope['tenantId'] as String,
          actorId: scope['ownerActorId'] as String,
          userId: (scope['canonicalActorId'] as String).substring(
            'actor:'.length,
          ),
          role: 'admin',
          apiBaseUrl: 'https://example.test',
        );
        final id = fixture['prepareRequest']['connectorId'] as String;
        final preparation =
            await ConnectorMcpRegistrationPreparationIntent.prepare(
              owner,
              connectorMap(fixture['prepareRequest']['declaration']),
              key: fixture['preparationKey'] as String,
              nonce: fixture['prepareRequest']['nonce'] as String,
            );
        expect(preparation.identity, fixture['preparationIntent']);
        expect(
          preparation.intentSha256,
          fixture['preparation']['intentSha256'],
        );
        expect(
          preparation.secretRequest(
            fixture['prepareRequest']['payload']['endpoint'] as String,
            fixture['prepareRequest']['payload']['bearerToken'] as String?,
          ),
          fixture['prepareRequest'],
        );
        expect(preparation.abandonRequest, fixture['abandonRequest']);
        final proof = await ConnectorMcpRegistrationPreparationProof.parse(
          fixture['preparation'],
          preparation,
        );
        expect(proof.raw, fixture['preparation']);
        expect(
          proof.freshAt(DateTime.parse(proof.raw['expiresAt'] as String)),
          isFalse,
        );
        for (final field in [
          'preparedReady',
          'preparedExpired',
          'preparedConsumed',
          'abandonedAbsent',
          'abandonedPrepared',
        ]) {
          final abandoned = field.startsWith('abandoned');
          for (final kind in ['read', abandoned ? 'abandon' : 'submit']) {
            final parsed = await ConnectorMcpRegistrationPreparationRead.parse(
              await registrationEnvelope(
                {
                  'prepared': fixture[field],
                  if (kind != 'read') 'replayed': true,
                },
                'mcpRegistrationPreparations',
                kind,
                owner: owner,
                key: kind == 'read' ? null : preparation.key,
                id: id,
              ),
              owner,
              intent: preparation,
              kind: kind,
            );
            expect(parsed.prepared, fixture[field]);
            if (field == 'abandonedAbsent') {
              expect(parsed.proof, isNull);
            } else {
              expect(parsed.proof!.sha256, proof.sha256);
            }
          }
        }
        final intent = await ConnectorMcpRegistrationIntent.create(
          preparation,
          proof,
          key: fixture['registrationKey'] as String,
        );
        expect(intent.request, fixture['registrationRequest']);
        expect(intent.identity, fixture['registrationIntent']);
        expect(
          intent.requestSha256,
          fixture['registrationAction']['acceptance']['requestSha256'],
        );
        final linked = await ConnectorMcpRegistrationIntent.create(
          preparation,
          proof,
          consumedKeySha256:
              fixture['preparedConsumed']['consumedKeySha256'] as String,
        );
        expect(linked.key, isNull);
        expect(linked.identity, intent.identity);
        for (final kind in ['submit', 'read']) {
          final parsed = await ConnectorMcpRegistrationRead.parse(
            await registrationEnvelope(
              {
                'action': fixture['registrationAction'],
                if (kind == 'submit') 'replayed': true,
              },
              'mcpRegistrations',
              kind,
              owner: owner,
              key: kind == 'submit' ? intent.key : null,
              id: id,
            ),
            owner,
            intent: kind == 'submit' ? intent : linked,
            kind: kind,
          );
          expect(parsed.action, fixture['registrationAction']);
          expect(parsed.settled, isTrue);
          expect(parsed.acceptance!['reviewSha256'], proof.sha256);
          expect(
            parsed.action!['settlement']['result']['credentialVersion'],
            name.startsWith('vault') ? 1 : 0,
          );
        }
        expect(jsonEncode(preparation.stored), isNot(contains('bearerToken')));
        expect(
          (await ConnectorMcpRegistrationIntent.restore(
            linked.stored,
            owner,
          )).key,
          isNull,
        );
      },
    );
  }

  test('TypeScript WHATWG normalization and safe projection retain exact escape case and empty delimiters', () {
    for (final raw in server['normalization'] as List) {
      final fixture = connectorMap(raw);
      expect(
        normalizeMcpRegistrationEndpoint(fixture['input'] as String),
        fixture['normalized'],
      );
      expect(mcpRegistrationEndpointProjection(fixture['input'] as String), {
        'endpoint': fixture['endpoint'],
        'endpointRedacted': fixture['endpointRedacted'],
      });
    }
    expect(
      normalizeMcpRegistrationEndpoint(
        "https://EXAMPLE.test:443/mcp?name=o'hare#plain'fragment",
      ),
      "https://example.test/mcp?name=o%27hare#plain'fragment",
    );
    for (final endpoint in [
      'https://user:secret@example.test/mcp',
      'https://example.test/private path',
      ' https://example.test/mcp',
      'https://example.test/mcp\n',
      'https://例え.test/mcp',
      'https://example.test/é',
      'https://[2001:4860:4860::8888]/mcp',
      'http://0177.0.0.1/mcp',
      'http://8.8.8.8./mcp',
    ]) {
      expect(
        () => normalizeMcpRegistrationEndpoint(endpoint),
        throwsFormatException,
      );
    }
  });

  test('safe declarations and payloads reject private material or mismatched authentication', () async {
    final declaration = registrationDeclaration();
    final intent = await ConnectorMcpRegistrationPreparationIntent.prepare(
      connectorOwner,
      declaration,
    );
    expect(
      jsonEncode(intent.stored),
      isNot(contains('synthetic-private-query')),
    );
    expect(jsonEncode(intent.stored), isNot(contains('synthetic-fragment')));
    expect(
      () => intent.secretRequest(
        'https://other.test/mcp?private',
        registrationToken,
      ),
      throwsFormatException,
    );
    expect(
      () => intent.secretRequest(registrationEndpoint, null),
      throwsFormatException,
    );
    for (final changed in [
      {...declaration, 'endpoint': registrationEndpoint},
      {...declaration, 'authType': 'none', 'authTokenEnv': 'TOKEN'},
      {...declaration, 'authType': 'bearer_env', 'authTokenEnv': null},
      {...declaration, 'authHeaderName': 'Authorization'},
      {
        ...declaration,
        'payload': {'bearerToken': registrationToken},
      },
    ]) {
      await expectLater(
        ConnectorMcpRegistrationPreparationIntent.prepare(
          connectorOwner,
          changed,
        ),
        throwsFormatException,
      );
    }
  });

  test('token limits are UTF-8 bytes with no trimming or line breaks', () {
    expect(mcpRegistrationTokenValid('éééé'), isTrue);
    expect(mcpRegistrationTokenValid('😀😀'), isTrue);
    expect(mcpRegistrationTokenValid('ééé'), isFalse);
    expect(mcpRegistrationTokenValid('é' * 4096), isTrue);
    expect(mcpRegistrationTokenValid('é' * 4097), isFalse);
    for (final value in [
      ' token123',
      'token123 ',
      'token\n123',
      'token\r123',
    ]) {
      expect(mcpRegistrationTokenValid(value), isFalse);
    }
  });
  test('safe preparation restores exact immutable scope and historical expired proof without any payload', () async {
    final intent = await ConnectorMcpRegistrationPreparationIntent.prepare(
      connectorOwner,
      registrationDeclaration(),
      key: 'prepare-one',
    );
    final restored = await ConnectorMcpRegistrationPreparationIntent.restore(
      intent.stored,
      connectorOwner,
    );
    expect(restored.intentSha256, intent.intentSha256);
    expect(jsonEncode(intent.stored), isNot(contains('payload')));
    expect(
      intent.secretRequest(
        registrationEndpoint,
        registrationToken,
      )['payload']['bearerToken'],
      registrationToken,
    );
    final proof = await registrationProof(intent);
    expect(proof.freshAt(registrationNow), isTrue);
    expect(
      proof.freshAt(registrationNow.add(const Duration(minutes: 15))),
      isFalse,
    );
    expect(
      (await ConnectorMcpRegistrationPreparationProof.parse(
        proof.raw,
        intent,
      )).sha256,
      proof.sha256,
    );
    final changed = {
      ...proof.raw,
      'expiresAt': registrationNow
          .add(const Duration(minutes: 16))
          .toIso8601String(),
    }..remove('preparationSha256');
    await expectLater(
      ConnectorMcpRegistrationPreparationProof.parse({
        ...changed,
        'preparationSha256': await connectorSha(changed),
      }, intent),
      throwsFormatException,
    );
    await expectLater(
      ConnectorMcpRegistrationPreparationIntent.restore({
        ...intent.stored,
        'identity': {
          ...intent.identity,
          'payload': {'bearerToken': registrationToken},
        },
      }, connectorOwner),
      throwsFormatException,
    );
  });
  test('prepared acceptance binds proof SHA, and receipt refuses a resealed unrelated preparation SHA', () async {
    final prep = await ConnectorMcpRegistrationPreparationIntent.prepare(
      connectorOwner,
      registrationDeclaration(),
    );
    final intent = await ConnectorMcpRegistrationIntent.create(
      prep,
      await registrationProof(prep),
    );
    final action = await registrationAction(intent);
    expect(action.acceptance!['reviewSha256'], intent.proof.sha256);
    final a = {...action.acceptance!, 'reviewSha256': 'a' * 64}
      ..remove('acceptanceSha256');
    final changed = {
      ...action.action!,
      'acceptance': {...a, 'acceptanceSha256': await connectorSha(a)},
    };
    final wire = await registrationEnvelope(
      {'action': changed},
      'mcpRegistrations',
      'read',
    );
    await expectLater(
      ConnectorMcpRegistrationRead.parse(wire, connectorOwner, intent: intent),
      throwsFormatException,
    );
  });
  test('consumed key correlation, abandonment tombstone and cleanup receipt action are strict', () async {
    final prep = await ConnectorMcpRegistrationPreparationIntent.prepare(
      connectorOwner,
      registrationDeclaration(),
    );
    final consumed = await registrationPreparation(
      prep,
      availability: 'consumed',
      consumedKey: 'a' * 64,
    );
    final changed = {...consumed.prepared!, 'consumedKeySha256': 'b' * 64};
    await expectLater(
      ConnectorMcpRegistrationPreparationRead.parse(
        await registrationEnvelope(
          {'prepared': changed},
          'mcpRegistrationPreparations',
          'read',
        ),
        connectorOwner,
        intent: prep,
      ),
      throwsFormatException,
    );
    final abandoned = await registrationPreparation(
      prep,
      kind: 'abandon',
      availability: 'abandoned',
      tombstone: true,
    );
    expect(abandoned.proof, isNull);
    expect(abandoned.prepared!['abandonment']['preparationSha256'], isNull);
    expect(abandoned.raw['serviceReceipt']['action'], 'read');
    expect(abandoned.raw['serviceReceipt']['accessMode'], 'mutation');
    final r = {
      ...connectorMap(abandoned.raw['serviceReceipt']),
      'action': 'manage.connector',
    }..remove('receiptSha256');
    await expectLater(
      ConnectorMcpRegistrationPreparationRead.parse(
        {
          ...abandoned.raw,
          'serviceReceipt': {...r, 'receiptSha256': await connectorSha(r)},
        },
        connectorOwner,
        intent: prep,
        kind: 'abandon',
      ),
      throwsFormatException,
    );
  });
  test('resealed settlement cannot change the authentication-bound credential version', () async {
    for (final auth in ['none', 'bearer_env', 'bearer_vault']) {
      final prep = await ConnectorMcpRegistrationPreparationIntent.prepare(
        connectorOwner,
        registrationDeclaration(authType: auth),
      );
      final intent = await ConnectorMcpRegistrationIntent.create(
        prep,
        await registrationProof(prep),
      );
      final action = await registrationAction(intent);
      final settlement = connectorMap(action.action!['settlement']);
      final changed = {
        ...settlement,
        'result': {
          ...connectorMap(settlement['result']),
          'credentialVersion': auth == 'bearer_vault' ? 0 : 1,
        },
      }..remove('settlementSha256');
      await expectLater(
        ConnectorMcpRegistrationRead.parse(
          await registrationEnvelope(
            {
              'action': {
                ...action.action!,
                'settlement': {
                  ...changed,
                  'settlementSha256': await connectorSha(changed),
                },
              },
            },
            'mcpRegistrations',
            'read',
            id: intent.id,
          ),
          connectorOwner,
          intent: intent,
        ),
        throwsFormatException,
      );
    }
  });

  test('linked action is immutable GET-only evidence and cannot parse a submit response', () async {
    final prep = await ConnectorMcpRegistrationPreparationIntent.prepare(
      connectorOwner,
      registrationDeclaration(),
    );
    final intent = await ConnectorMcpRegistrationIntent.create(
      prep,
      await registrationProof(prep),
      consumedKeySha256: 'a' * 64,
    );
    final restored = await ConnectorMcpRegistrationIntent.restore(
      intent.stored,
      connectorOwner,
    );
    expect(restored.key, isNull);
    expect(restored.requestSha256, intent.requestSha256);
    final action = await registrationAction(restored);
    expect(action.settled, isTrue);
    await expectLater(
      ConnectorMcpRegistrationRead.parse(
        action.raw,
        connectorOwner,
        intent: restored,
        kind: 'submit',
      ),
      throwsFormatException,
    );
  });
}
