import 'dart:convert';
import 'dart:io';

import 'package:asael/features/integrations/connector_contracts.dart';
import 'package:asael/features/integrations/connector_control_contracts.dart';
import 'package:asael/features/integrations/connector_credential_rotation_contracts.dart';
import 'package:flutter_test/flutter_test.dart';

import 'connector_credential_removal_fixtures.dart';
import 'connector_credential_rotation_fixtures.dart';
import 'connector_fixtures.dart';

void main() {
  // Independent TypeScript exports were parsed/resealed by the server schemas;
  // their domain hashes are never regenerated by the Dart fixture builders.
  final server = connectorMap(
    jsonDecode(
      File('test/fixtures/connector_credential_rotation/server.json')
          .readAsStringSync(),
    ),
  );
  for (final name in ['configured', 'unconfigured']) {
    test(
      'TypeScript $name preparation, abandonment and rotation retain exact Dart identity and hashes',
      () async {
        final fixture = connectorMap(server[name]),
            scope = connectorMap(fixture['scope']);
        final owner = ConnectorOwner(
          tenantId: scope['tenantId'] as String,
          actorId: scope['ownerActorId'] as String,
          userId: (scope['canonicalActorId'] as String).substring(
            'actor:'.length,
          ),
          role: 'admin',
          apiBaseUrl: 'https://example.test',
        );
        final id = fixture['prepareRequest']['connectorId'] as String;
        final review = await ConnectorReview.parse(
          await connectorEnvelope(
            {'review': fixture['review']},
            'review',
            owner: owner,
          ),
          owner,
          'mcp',
          id,
        );
        expect(credentialRotationEligible(review), isTrue);
        final preparation = await ConnectorCredentialPreparationIntent.prepare(
          owner,
          review,
          key: fixture['preparationKey'] as String,
          nonce: fixture['prepareRequest']['nonce'] as String,
        );
        expect(preparation.identity, fixture['preparationIntent']);
        expect(
          preparation.intentSha256,
          fixture['preparation']['intentSha256'],
        );
        expect(
          preparation.secretRequest(
            fixture['prepareRequest']['payload']['bearerToken'] as String,
          ),
          fixture['prepareRequest'],
        );
        expect(preparation.abandonRequest, fixture['abandonRequest']);
        final proof = await ConnectorCredentialPreparationProof.parse(
          fixture['preparation'],
          preparation,
        );
        expect(proof.raw, fixture['preparation']);
        expect(
          proof.freshAt(DateTime.parse(proof.raw['expiresAt'] as String)),
          isFalse,
        );
        for (final field in [
          'preparedReady',
          'preparedExpired',
          'preparedConsumed',
          'abandonedAbsent',
          'abandonedPrepared',
        ]) {
          final abandoned = field.startsWith('abandoned');
          for (final kind in ['read', abandoned ? 'abandon' : 'submit']) {
            final parsed = await ConnectorCredentialPreparationRead.parse(
              await rotationEnvelope(
                {
                  'prepared': fixture[field],
                  if (kind != 'read') 'replayed': true,
                },
                'credentialPreparations',
                kind,
                owner: owner,
                key: kind == 'read' ? null : preparation.key,
                id: id,
              ),
              owner,
              intent: preparation,
              kind: kind,
            );
            expect(parsed.prepared, fixture[field]);
            if (field == 'abandonedAbsent') {
              expect(parsed.proof, isNull);
            } else {
              expect(parsed.proof!.sha256, proof.sha256);
            }
          }
        }
        final intent = await ConnectorCredentialRotationIntent.create(
          preparation,
          proof,
          key: fixture['rotationKey'] as String,
        );
        expect(intent.request, fixture['rotationRequest']);
        expect(intent.identity, fixture['rotationIntent']);
        expect(
          intent.requestSha256,
          fixture['rotationAction']['acceptance']['requestSha256'],
        );
        final linked = await ConnectorCredentialRotationIntent.create(
          preparation,
          proof,
          consumedKeySha256:
              fixture['preparedConsumed']['consumedKeySha256'] as String,
        );
        expect(linked.key, isNull);
        expect(linked.identity, intent.identity);
        for (final kind in ['submit', 'read']) {
          final parsed = await ConnectorCredentialRotationRead.parse(
            await rotationEnvelope(
              {
                'action': fixture['rotationAction'],
                if (kind == 'submit') 'replayed': true,
              },
              'credentialRotations',
              kind,
              owner: owner,
              key: kind == 'submit' ? intent.key : null,
              id: id,
            ),
            owner,
            intent: kind == 'submit' ? intent : linked,
            kind: kind,
          );
          expect(parsed.action, fixture['rotationAction']);
          expect(parsed.settled, isTrue);
          expect(parsed.acceptance!['reviewSha256'], proof.sha256);
          expect(
            parsed.action!['settlement']['result']['credentialVersion'],
            name == 'configured' ? 3 : 1,
          );
        }
        expect(jsonEncode(preparation.stored), isNot(contains('bearerToken')));
        expect(
          (await ConnectorCredentialRotationIntent.restore(
            linked.stored,
            owner,
          )).key,
          isNull,
        );
      },
    );
  }

  test('token limits are UTF-8 bytes with no trimming or line breaks', () {
    expect(credentialRotationTokenValid('éééé'), isTrue);
    expect(credentialRotationTokenValid('😀😀'), isTrue);
    expect(credentialRotationTokenValid('ééé'), isFalse);
    expect(credentialRotationTokenValid('é' * 4096), isTrue);
    expect(credentialRotationTokenValid('é' * 4097), isFalse);
    for (final value in [
      ' token123',
      'token123 ',
      'token\n123',
      'token\r123',
    ]) {
      expect(credentialRotationTokenValid(value), isFalse);
    }
  });
  test('safe preparation restores exact immutable scope and historical expired proof without any payload', () async {
    final review = await removalReviewFixture();
    final intent = await ConnectorCredentialPreparationIntent.prepare(
      connectorOwner,
      review,
      key: 'prepare-one',
    );
    final restored = await ConnectorCredentialPreparationIntent.restore(
      intent.stored,
      connectorOwner,
    );
    expect(restored.intentSha256, intent.intentSha256);
    expect(jsonEncode(intent.stored), isNot(contains('payload')));
    expect(
      intent.secretRequest(rotationToken)['payload']['bearerToken'],
      rotationToken,
    );
    final proof = await rotationProof(intent);
    expect(proof.freshAt(rotationNow), isTrue);
    expect(
      proof.freshAt(rotationNow.add(const Duration(minutes: 15))),
      isFalse,
    );
    expect(
      (await ConnectorCredentialPreparationProof.parse(
        proof.raw,
        intent,
      )).sha256,
      proof.sha256,
    );
    final changed = {
      ...proof.raw,
      'expiresAt': rotationNow
          .add(const Duration(minutes: 16))
          .toIso8601String(),
    }..remove('preparationSha256');
    await expectLater(
      ConnectorCredentialPreparationProof.parse({
        ...changed,
        'preparationSha256': await connectorSha(changed),
      }, intent),
      throwsFormatException,
    );
    await expectLater(
      ConnectorCredentialPreparationIntent.restore({
        ...intent.stored,
        'identity': {
          ...intent.identity,
          'payload': {'bearerToken': rotationToken},
        },
      }, connectorOwner),
      throwsFormatException,
    );
  });
  test('prepared acceptance binds proof SHA, and receipt refuses a resealed original review SHA', () async {
    final prep = await ConnectorCredentialPreparationIntent.prepare(
      connectorOwner,
      await removalReviewFixture(),
    );
    final intent = await ConnectorCredentialRotationIntent.create(
      prep,
      await rotationProof(prep),
    );
    final action = await rotationAction(intent);
    expect(action.acceptance!['reviewSha256'], intent.proof.sha256);
    final a = {
      ...action.acceptance!,
      'reviewSha256': intent.review['reviewSha256'],
    }..remove('acceptanceSha256');
    final changed = {
      ...action.action!,
      'acceptance': {...a, 'acceptanceSha256': await connectorSha(a)},
    };
    final wire = await rotationEnvelope(
      {'action': changed},
      'credentialRotations',
      'read',
    );
    await expectLater(
      ConnectorCredentialRotationRead.parse(
        wire,
        connectorOwner,
        intent: intent,
      ),
      throwsFormatException,
    );
  });
  test('consumed key correlation, abandonment tombstone and cleanup receipt action are strict', () async {
    final prep = await ConnectorCredentialPreparationIntent.prepare(
      connectorOwner,
      await removalReviewFixture(),
    );
    final consumed = await rotationPreparation(
      prep,
      availability: 'consumed',
      consumedKey: 'a' * 64,
    );
    final changed = {...consumed.prepared!, 'consumedKeySha256': 'b' * 64};
    await expectLater(
      ConnectorCredentialPreparationRead.parse(
        await rotationEnvelope(
          {'prepared': changed},
          'credentialPreparations',
          'read',
        ),
        connectorOwner,
        intent: prep,
      ),
      throwsFormatException,
    );
    final abandoned = await rotationPreparation(
      prep,
      kind: 'abandon',
      availability: 'abandoned',
      tombstone: true,
    );
    expect(abandoned.proof, isNull);
    expect(abandoned.prepared!['abandonment']['preparationSha256'], isNull);
    expect(abandoned.raw['serviceReceipt']['action'], 'read');
    expect(abandoned.raw['serviceReceipt']['accessMode'], 'mutation');
    final r = {
      ...connectorMap(abandoned.raw['serviceReceipt']),
      'action': 'manage.connector',
    }..remove('receiptSha256');
    await expectLater(
      ConnectorCredentialPreparationRead.parse(
        {
          ...abandoned.raw,
          'serviceReceipt': {...r, 'receiptSha256': await connectorSha(r)},
        },
        connectorOwner,
        intent: prep,
        kind: 'abandon',
      ),
      throwsFormatException,
    );
  });
  test('linked action is immutable GET-only evidence and cannot parse a submit response', () async {
    final prep = await ConnectorCredentialPreparationIntent.prepare(
      connectorOwner,
      await removalReviewFixture(),
    );
    final intent = await ConnectorCredentialRotationIntent.create(
      prep,
      await rotationProof(prep),
      consumedKeySha256: 'a' * 64,
    );
    final restored = await ConnectorCredentialRotationIntent.restore(
      intent.stored,
      connectorOwner,
    );
    expect(restored.key, isNull);
    expect(restored.requestSha256, intent.requestSha256);
    final action = await rotationAction(restored);
    expect(action.settled, isTrue);
    await expectLater(
      ConnectorCredentialRotationRead.parse(
        action.raw,
        connectorOwner,
        intent: restored,
        kind: 'submit',
      ),
      throwsFormatException,
    );
  });
}
