"use client";

import { at, count, rows, sloLabel, text } from "./operational-contracts";
import { ActionForm, DataRows, DataSection, Facts, OperationalFrame, RecordHeading, ScopedOperationalWorkspace, styles, useOperationalWorkspace, type Endpoint } from "./operational-view";
const endpoints: readonly Endpoint[] = [
  { key: "events", label: "Runtime events", path: "/api/observability?limit=24", permission: "read.security", coverage: "Up to 24 recent runtime events, with the server's aggregate statistics." },
  { key: "slo", label: "SLO snapshot", path: "/api/observability/slo", permission: "read.security", coverage: "A measured policy snapshot; policies with insufficient samples are not health proof." },
  { key: "incidents", label: "Active incidents", path: "/api/incidents?status=active&limit=12", permission: "read.security", coverage: "Up to 12 active incidents. Resolved history is outside this view." },
  { key: "alerts", label: "Alert deliveries", path: "/api/alerts?limit=12", permission: "read.security", coverage: "Up to 12 recent alert deliveries. Reading does not dispatch them." },
];
export function MonitoringWorkspace({ embedded = false }: { embedded?: boolean } = {}) { return <ScopedOperationalWorkspace><MonitoringView embedded={embedded} /></ScopedOperationalWorkspace>; }
function MonitoringView({ embedded }: { embedded: boolean }) {
  const api = useOperationalWorkspace(endpoints); const slo = api.resources.slo; const events = api.resources.events;
  return <OperationalFrame embedded={embedded} title="Monitoring" description="Read the latest available runtime evidence, SLO measurements, incidents, and alert delivery outcomes." api={api}>
    <div className={styles.summary}><p className={styles.support}>Values reflect each source’s last loaded snapshot. Source states below show refresh failures and unavailable reads.</p><Facts values={[["SLO snapshot", slo?.data ? sloLabel(slo.data) : "Unavailable"], ["Runtime events", count(at(events?.data, "stats.total"))], ["Active incidents", count(at(api.resources.incidents?.data, "stats.active"))], ["Alert delivery failures", count(at(api.resources.alerts?.data, "stats.failed"))]]} /></div>
    <div className={styles.columns}><div className={styles.mainColumn}>
      <DataSection title="SLO measurements" source={slo} description="A healthy flag means no measured breach in this snapshot. Missing samples and unavailable reads remain explicit."><p className={styles.reading}>{sloLabel(slo?.data)}</p><Facts values={[["Checked", slo?.data?.checkedAt]]} /><DataRows items={rows(slo?.data?.evaluations)} empty="No policy measurements in this loaded snapshot." render={(item) => <><RecordHeading title={at(item, "policy.name")} status={item.insufficientSamples ? "Insufficient samples" : item.breached === true ? "Breached" : "No breach reported"} /><p>{text(item.message)}</p><Facts values={[["Policy ID", at(item, "policy.id")], ["Metric", at(item, "policy.metric")], ["Measured value", item.value], ["Threshold", item.threshold], ["Unit", at(item, "policy.unit")], ["Severity", item.severity], ["Samples", at(item, "insufficientSamples.samples")], ["Required samples", at(item, "insufficientSamples.minimumSamples")]]} /></>} /></DataSection>
      <DataSection title="Active incidents" source={api.resources.incidents}><DataRows items={rows(api.resources.incidents?.data?.incidents)} empty="No active incidents in this loaded view." render={(item) => <><RecordHeading title={item.title} status={item.status} /><p>{text(item.message)}</p><Facts values={[["Incident ID", item.id], ["Component", item.componentId], ["Severity", item.severity], ["Occurrences", item.occurrenceCount], ["Fingerprint", item.fingerprint], ["First seen", item.firstSeenAt], ["Last seen", item.lastSeenAt], ["Acknowledged by", item.acknowledgedBy], ["Acknowledgement reason", item.acknowledgementReason]]} /></>} /></DataSection>
      <DataSection title="Alert deliveries" source={api.resources.alerts} description="Queued, running, delivered, failed, and skipped are distinct delivery outcomes."><DataRows items={rows(api.resources.alerts?.data?.deliveries)} empty="No alert deliveries in this loaded view." render={(item) => <><RecordHeading title={item.channel} status={item.status} /><Facts values={[["Delivery ID", item.id], ["Incident ID", item.incidentId], ["Incident event", item.incidentEventId], ["Target ID", item.targetId], ["Attempt", item.attempt], ["Maximum attempts", item.maxAttempts], ["Scheduled", item.runAt], ["Updated", item.updatedAt], ["Delivered", item.deliveredAt]]} />{item.lastError ? <p>{text(item.lastError)}</p> : null}</>} /></DataSection>
      <DataSection title="Runtime timeline" source={events} description="The latest 24 events. Event severity is evidence about that event, not a global health indicator."><DataRows items={rows(events?.data?.events)} empty="No runtime events in this loaded view." render={(item) => <><RecordHeading title={item.message || item.action} status={item.level} /><Facts values={[["Event ID", item.id], ["Action", item.action], ["Category", item.category], ["Route", item.route], ["HTTP status", item.statusCode], ["Duration (ms)", item.durationMs], ["Request ID", item.requestId], ["Correlation ID", item.correlationId], ["Actor", item.actorId], ["Resource ID", item.resourceId], ["Recorded", item.createdAt]]} /></>} /></DataSection>
    </div><aside className={styles.sideColumn} aria-label="Monitoring controls">
      <ActionForm kind="monitor" api={api} description="Evaluate SLO policies and update matching incidents, including resolving recovered incidents. Queueing can schedule notifications; dispatch can send pending alerts to configured external targets." initial={{ queueAlerts: true, dispatchAlerts: false }} fields={[{ name: "queueAlerts", label: "Queue alerts for breached policies", type: "checkbox" }, { name: "dispatchAlerts", label: "Dispatch pending alerts now (up to 10)", type: "checkbox" }]} preview={<p>This endpoint has no request replay guarantee. A lost response may leave incidents or notifications changed. Dispatch can include pending alerts that predate this monitor request.</p>} />
      <ActionForm kind="marker" api={api} description="Record an operator marker in the runtime timeline. Avoid secrets; the server may redact the recorded text." initial={{ message: "", level: "info", category: "system" }} fields={[{ name: "message", label: "Marker message", type: "textarea", minLength: 1, maxLength: 240 }, { name: "level", label: "Severity", type: "select", options: [["info", "Info"], ["warn", "Warning"], ["error", "Error"]] }, { name: "category", label: "Category", type: "select", options: [["system", "System"], ["workflow", "Workflow"], ["connector", "Connector"], ["security", "Security"], ["evaluation", "Evaluation"]] }]} />
    </aside></div>
  </OperationalFrame>;
}
