"use client";

import { at, count, rows, text } from "./operational-contracts";
import { ActionForm, DataRows, DataSection, Facts, OperationalFrame, RecordHeading, ReleaseEvidence, ScopedOperationalWorkspace, styles, useOperationalWorkspace, type Endpoint } from "./operational-view";

const endpoints: readonly Endpoint[] = [
  { key: "evaluations", label: "Evaluation runs and cases", path: "/api/evaluations?limit=12", permission: "read", coverage: "Up to 12 recent runs and jobs, plus the server's case catalog." },
  { key: "feedback", label: "Failure feedback", path: "/api/evaluations/failure-feedback?limit=50", permission: "read", coverage: "Up to 50 failure clusters and proposals in this tenant." },
  { key: "release", label: "Release evidence", path: "/api/release/evidence", permission: "read.security", coverage: "Current server gate report. May reuse the server's cached assessment." },
];
export function QualityWorkspace({ embedded = false }: { embedded?: boolean } = {}) { return <ScopedOperationalWorkspace><QualityView embedded={embedded} /></ScopedOperationalWorkspace>; }
function QualityView({ embedded }: { embedded: boolean }) {
  const api = useOperationalWorkspace(endpoints); const evaluations = api.resources.evaluations; const feedback = api.resources.feedback;
  const clusters = rows(feedback?.data?.clusters); const proposals = rows(feedback?.data?.proposals);
  return <OperationalFrame embedded={embedded} title="Quality Checks" description="Inspect measured evaluations, recurring failures, and proposed harness changes. Review their evidence before another governed run." api={api}>
    <div className={styles.summary} aria-label="Quality snapshot"><p className={styles.support}>Values reflect each source’s last loaded snapshot. Source states below show refresh failures and unavailable reads.</p><Facts values={[["Recorded runs", count(at(evaluations?.data, "stats.total"))], ["Cases in loaded catalog", evaluations?.data ? rows(evaluations.data.cases).length : "Unavailable"], ["Active recurring failures", count(at(feedback?.data, "summary.activeRecurring"))], ["Proposed rules", count(at(feedback?.data, "summary.proposedRules"))]]} /></div>
    <div className={styles.columns}><div className={styles.mainColumn}>
      <DataSection title="Evaluation runs" source={evaluations} description="A completed run can contain failed or warning results. Run status is separate from case outcomes.">
        <DataRows items={rows(evaluations?.data?.runs)} empty="No evaluation runs in this loaded view." render={(run) => <><RecordHeading title={run.suite} status={run.status} /><Facts values={[["Run ID", run.id], ["Passed", count(at(run, "summary.passed"))], ["Failed", count(at(run, "summary.failed"))], ["Warnings", count(at(run, "summary.warnings"))], ["Total cases", count(at(run, "summary.total"))], ["Created", run.createdAt], ["Completed", run.completedAt]]} />{run.error ? <p>{text(run.error)}</p> : null}<details><summary>Timing and cost</summary><Facts values={[["Average latency (ms)", at(run, "summary.averageLatencyMs")], ["Estimated cost (USD)", at(run, "summary.estimatedCostUsd")]]} /></details></>} />
      </DataSection>
      <DataSection title="Evaluation jobs" source={evaluations} description="Only the bounded job list is shown. An absent job is not proof of completion."><DataRows items={rows(evaluations?.data?.jobs)} empty="No evaluation jobs in this loaded view." render={(job) => <><RecordHeading title={job.type} status={job.status} /><Facts values={[["Job ID", job.id], ["Attempt", job.attempt], ["Maximum attempts", job.maxAttempts], ["Updated", job.updatedAt], ["Completed", job.completedAt], ["Run ID", at(job, "result.evalRunId")]]} />{job.lastError ? <p>{text(job.lastError)}</p> : null}</>} /></DataSection>
      <DataSection title="Recurring failures" source={feedback} description="Replay selects the current case only when its definition still matches the stored digest."><DataRows items={clusters} empty="No failure clusters in this loaded view." render={(cluster) => <><RecordHeading title={cluster.caseId} status={cluster.status} /><Facts values={[["Cluster ID", cluster.id], ["Failure category", cluster.failureCategory], ["Failures", count(cluster.failureCount)], ["Consecutive failures", count(cluster.consecutiveFailures)], ["Latest run", cluster.latestEvalRunId], ["Latest result", cluster.latestResultId], ["Updated", cluster.updatedAt]]} /><details><summary>Replay identity</summary><Facts values={[["Case definition SHA-256", at(cluster, "replayCase.caseDefinitionSha256")], ["Replay SHA-256", cluster.replayCaseSha256], ["Failure signal SHA-256", at(cluster, "replayCase.failureSignalSha256")], ["Mutation authority", at(cluster, "replayCase.replay.mutationAuthority")]]} /></details></>} /></DataSection>
      <DataSection title="Harness rule proposals" source={feedback} description="Approval records a review. It never applies code, prompts, or workflow changes."><DataRows items={proposals} empty="No harness proposals in this loaded view." render={(proposal) => <><RecordHeading title={proposal.target} status={proposal.status} /><Facts values={[["Proposal ID", proposal.id], ["Version", proposal.version], ["Kind", proposal.kind], ["Cluster ID", proposal.clusterId], ["Proposal SHA-256", proposal.proposalSha256], ["Proposed", proposal.proposedAt], ["Reviewed by", proposal.reviewedBy], ["Reviewed", proposal.reviewedAt]]} />{proposal.reviewReason ? <p>{text(proposal.reviewReason)}</p> : null}<details><summary>Proposed change</summary><Facts values={[["Operation", at(proposal, "proposal.change.operation")], ["Scope", at(proposal, "proposal.change.scope")], ["Automatic application", at(proposal, "proposal.automaticApplication")]]} /></details></>} /></DataSection>
      <ReleaseEvidence source={api.resources.release} />
      <DataSection title="Case catalog" source={evaluations} description="Governance describes possible case effects. This form does not supply a mutation override."><DataRows items={rows(evaluations?.data?.cases)} empty="No cases in the loaded catalog." render={(item) => <><RecordHeading title={item.name} status={at(item, "governance.safetyMode")} /><p>{text(item.description)}</p><Facts values={[["Case ID", item.id], ["Type", item.type], ["Risk level", at(item, "governance.riskLevel")], ["Writes to database", at(item, "governance.writesToDatabase")], ["Cleanup", at(item, "governance.cleanup")], ["Admin required", at(item, "governance.production.requiresAdmin")], ["Mutation approval required", at(item, "governance.production.requiresMutationApproval")]]} /></>} /></DataSection>
    </div><aside className={styles.sideColumn} aria-label="Quality controls">
      <ActionForm kind="run" api={api} description="Queue an operational evaluation. Read-only and synthetic cases can still persist evaluation records. Mutation-capable cases remain subject to the server's explicit governance; this form grants no override." initial={{ suite: "operator-console", maxSafetyMode: "synthetic" }} fields={[{ name: "suite", label: "Suite name", minLength: 1, maxLength: 80 }, { name: "maxSafetyMode", label: "Maximum safety mode", type: "select", options: [["read_only", "Read only"], ["synthetic", "Synthetic"], ["mutation_allowed", "Mutation capable · no override"]] }]} />
      <ActionForm kind="review" api={api} description="Record an approval or rejection for the exact proposal ID. Already-reviewed proposals may conflict; refresh to inspect their current state." initial={{ proposalId: "", decision: "approved", reason: "" }} target={(draft) => proposals.find((row) => row.id === String(draft.proposalId).trim())} fields={[{ name: "proposalId", label: "Proposal ID", minLength: 1, maxLength: 240 }, { name: "decision", label: "Decision", type: "select", options: [["approved", "Approve"], ["rejected", "Reject"]] }, { name: "reason", label: "Review reason", type: "textarea", minLength: 12, maxLength: 500, help: "12–500 characters. The server records the exact trimmed reason." }]} />
      <ActionForm kind="replay" api={api} description="Queue the stored cluster's minimized case. Changed case definitions return a conflict. Mutation authority is never inherited from the failed run." initial={{ clusterId: "" }} target={(draft) => clusters.find((row) => row.id === String(draft.clusterId).trim())} fields={[{ name: "clusterId", label: "Failure cluster ID", minLength: 1, maxLength: 240 }]} />
    </aside></div>
  </OperationalFrame>;
}
