"use client";

import { at, record, retentionKeys, rows, text } from "./operational-contracts";
import { ActionForm, DataRows, DataSection, Facts, OperationalFrame, RecordHeading, ReleaseEvidence, ScopedOperationalWorkspace, styles, useOperationalWorkspace, type Endpoint } from "./operational-view";
const endpoints: readonly Endpoint[] = [
  { key: "context", label: "Access context", path: "/api/security/context", permission: "read", coverage: "Current scoped identity and role rules. This read does not change access." },
  { key: "audits", label: "Security audit", path: "/api/security/audits?limit=24", permission: "read.security", coverage: "Up to 24 recent audit records in this tenant." },
  { key: "isolation", label: "Tenant isolation", path: "/api/security/isolation-report", permission: "read.security", coverage: "Current storage and table-policy assessment; not proof of every application path." },
  { key: "retention", label: "Retention policy", path: "/api/security/retention", permission: "read.security", coverage: "Read-only policy and backend description. No eligible-record count or server-bound preview is provided." },
  { key: "release", label: "Release evidence", path: "/api/release/evidence", permission: "read.security", coverage: "Current server gate report. May reuse the server's cached assessment." },
];
export function SecurityWorkspace() { return <ScopedOperationalWorkspace><SecurityView /></ScopedOperationalWorkspace>; }
function SecurityView() {
  const api = useOperationalWorkspace(endpoints); const context = api.resources.context; const retention = api.resources.retention; const isolation = record(api.resources.isolation?.data?.report);
  const exportReason = api.blocked("read.security");
  return <OperationalFrame title="Security" description="Inspect access, audit evidence, tenant isolation, and retention. Review the exact scope before changing retained data." api={api}>
    <div className={styles.columns}><div className={styles.mainColumn}>
      <DataSection title="Access and role rules" source={context}><Facts values={[["Tenant", at(context?.data, "context.tenantId")], ["Actor", at(context?.data, "context.actorId")], ["Role", at(context?.data, "context.role")]]} /><ul className={styles.rows}>{Object.entries(record(at(context?.data, "policy.rbacRules"))).map(([role, actions]) => <li key={role}><RecordHeading title={role} /><p>{Array.isArray(actions) ? actions.map((action) => text(action)).join(", ") : "Rule details unavailable"}</p></li>)}</ul></DataSection>
      <DataSection title="Security audit" source={api.resources.audits} description="Decisions preserve their exact allow, deny, or other reported status. This is a bounded recent view."><DataRows items={rows(api.resources.audits?.data?.records)} empty="No audit records in this loaded view." render={(item) => <><RecordHeading title={item.action} status={item.decision} /><Facts values={[["Audit ID", item.id], ["Actor", item.actorId], ["Actor role", item.actorRole], ["Resource type", item.resourceType], ["Resource ID", item.resourceId], ["Risk level", item.riskLevel], ["Recorded", item.createdAt]]} />{item.reason ? <p>{text(item.reason)}</p> : null}</>} /></DataSection>
      <DataSection title="Tenant isolation" source={api.resources.isolation}><RecordHeading title="Storage policy assessment" status={isolation.status} /><Facts values={[["Tenant", isolation.tenantId], ["Checked", isolation.checkedAt], ["Storage backend", isolation.storageBackend], ["Database configured", isolation.databaseConfigured], ["Expected tables", at(isolation, "summary.expectedTables")], ["Protected tables", at(isolation, "summary.protectedTables")], ["Failing tables", at(isolation, "summary.failingTables")]]} />{Array.isArray(isolation.recommendations) ? <ul>{isolation.recommendations.map((item, index) => <li key={index}>{text(item)}</li>)}</ul> : null}<details><summary>Table policy evidence</summary><DataRows items={rows(isolation.tables)} empty="No table evidence in this snapshot." render={(table) => <><RecordHeading title={table.tableName} status={table.status} /><Facts values={[["Category", table.category], ["Table exists", table.exists], ["Tenant column", table.tenantColumn], ["RLS enabled", table.rlsEnabled], ["RLS forced", table.forceRls], ["Policy present", table.policyPresent]]} /></>} /></details></DataSection>
      <ReleaseEvidence source={api.resources.release} />
    </div><aside className={styles.sideColumn} aria-label="Security controls and retention">
      <section className={styles.actionPanel} aria-labelledby="signed-audit-title"><h2 id="signed-audit-title">Signed audit chain</h2><p>Download a chronologically chained, HMAC-signed audit export for offline verification. Downloading alone does not verify its signature.</p>{exportReason ? <><button type="button" className={styles.button} disabled>Download signed audit</button><p>{exportReason}</p></> : <a className={styles.button} href="/api/security/audits/export" download>Download signed audit</a>}</section>
      <DataSection title="Retention policy" source={retention} description="All values are retention windows in days. Eligibility and actual deletion counts are determined by the server when a sweep runs."><Facts values={[["Backend", retention?.data?.backend], ["Automatic sweep", retention?.data?.automaticSweep]]} /><dl className={styles.facts}>{retentionKeys.map((key) => <div key={key}><dt>{key}</dt><dd>{text(at(retention?.data, `policy.${key}`))} days</dd></div>)}</dl></DataSection>
      <ActionForm kind="retention" api={api} description="Delete expired sensitive data in the current tenant using the server's policy and bounded sweep. This can remove records and payloads; it is not reversible from this view." disabledReason={!retention?.data || retention.error || retention.loading ? "Load a current retention policy before reviewing a sweep." : undefined} target={() => retention?.data ? { ...retention.data, receivedAt: retention.receivedAt } : undefined} preview={<p>This is a local review of the last loaded policy, not a server-bound deletion preview. The request sends only scope: tenant. The server applies its policy at execution time; no affected-record count, policy lock, or replay guarantee is available.</p>} />
    </aside></div>
  </OperationalFrame>;
}
