import type { AppServiceOperationContract } from "@/lib/app-services/contracts";
import { canonicalJsonSha256 } from "@/lib/tools/effect-receipt";

export const APP_SERVICE_REGISTRY_VERSION =
  "p9.1-app-service-registry:1" as const;

const readOnlyEventContract = "read_only:no_domain_mutation";

export const APP_SERVICE_OPERATION_CONTRACTS = Object.freeze([
  read("app.workspaces.summary", "read", "workspace"),
  read("app.workspaces.readiness", "read", "workspace"),
  read("app.integrations.overview.show", "read", "integrations_overview"),
  read("app.sources.coverage.show", "read", "source_coverage"),
  read("app.market_research.overview.show", "read", "market_research"),
  read("app.market_research.bars.list", "read", "market_snapshot"),
  read("app.market_research.features.show", "read", "market_technical_features"),
  read("app.market_research.analysis.list", "read", "market_analysis_version"),
  mutation("app.market_research.analysis.generate", "run.agent", "market_analysis_version", "market-analysis-version-events.v1"),
  read("app.market_research.events.list", "read", "market_event_history"),
  mutation("app.market_research.events.backfill", "manage.workflow", "market_event_history", "market-macro-event-events.v1"),
  read("app.market_research.replays.list", "read", "market_event_replay"),
  mutation("app.market_research.replays.backfill", "manage.workflow", "market_event_replay", "market-event-replay-events.v1"),
  read("app.market_research.baselines.show", "read", "market_event_baseline"),
  read("app.market_research.journal.list", "read", "market_forecast_journal"),
  mutation("app.market_research.journal.generate", "run.agent", "market_forward_forecast", "market-forward-shadow-events.v1"),
  mutation("app.market_research.journal.score", "manage.workflow", "market_forecast_outcome", "market-forward-shadow-events.v1"),
  read("app.library.list", "read", "workspace_library"),
  read("app.memory.readable.show", "read", "memory_overview"),
  read("app.memory.intelligence.show", "read", "memory_intelligence"),
  read("app.memory.shared.list", "read", "shared_memory"),
  mutation("app.memory.shared.write", "write.memory", "shared_memory", "memory.atomic-events.v1"),
  read("app.workspace_templates.list", "read", "workspace_template"),
  mutation("app.workspace_templates.publish", "manage.workflow", "workspace_template", "workspace-template-events.v1"),
  mutation("app.workspace_templates.instantiate", "run.agent", "project", "workspace-template-events.v1+projects.atomic-events.v1"),
  read("app.meetings.list", "read", "meeting"),
  read("app.meetings.show", "read", "meeting"),
  mutation("app.meetings.create", "manage.workflow", "meeting", "meeting-events.v1"),
  mutation("app.meetings.update", "manage.workflow", "meeting", "meeting-events.v1"),
  read("app.meetings.commitments.list", "read", "meeting_commitment"),
  mutation("app.meetings.commitments.propose", "run.agent", "meeting_commitment", "meeting-commitment-events.v1"),
  mutation("app.meetings.commitments.resolve", "manage.workflow", "meeting_commitment", "meeting-commitment-events.v1+projects.atomic-events.v1+governed-communication-events.v1"),
  read("app.customer_accounts.list", "read", "customer_account"),
  read("app.customer_accounts.show", "read", "customer_account"),
  read("app.customer_accounts.portfolio.show", "read", "customer_success_portfolio"),
  read("app.customer_accounts.intelligence.show", "read", "customer_success_intelligence"),
  mutation("app.customer_accounts.create", "manage.workflow", "customer_account", "customer-account-events.v1"),
  mutation("app.customer_accounts.revise", "manage.workflow", "customer_account", "customer-account-events.v1"),
  mutation("app.customer_accounts.facts.record", "manage.workflow", "customer_account_fact", "customer-account-events.v1"),
  read("app.customer_accounts.health.show", "read", "customer_health_score"),
  mutation("app.customer_accounts.health.evaluate", "manage.workflow", "customer_health_score", "customer-health-events.v1"),
  read("app.customer_accounts.workflows.list", "read", "customer_success_workflow"),
  mutation("app.customer_accounts.workflows.start", "run.agent", "customer_success_workflow", "customer-success-workflow-events.v1+projects.atomic-events.v1"),
  mutation("app.customer_accounts.workflows.outcome.record", "manage.workflow", "customer_success_workflow_outcome", "customer-success-workflow-events.v1"),
  mutation("app.customer_accounts.salesforce.writes.configure", "manage.connector", "salesforce_write_configuration", "customer-account-events.v1"),
  mutation("app.customer_accounts.salesforce.contact.create", "manage.connector", "salesforce_contact", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.contact.update", "manage.connector", "salesforce_contact", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.task.create", "manage.connector", "salesforce_task", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.task.update", "manage.connector", "salesforce_task", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.note.update", "manage.connector", "salesforce_note", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.case.create", "manage.connector", "salesforce_case", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.case.update", "manage.connector", "salesforce_case", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.opportunity.create", "manage.connector", "salesforce_opportunity", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.opportunity.update", "manage.connector", "salesforce_opportunity", "salesforce-guarded-write-events.v1"),
  mutation("app.customer_accounts.salesforce.account.update", "manage.connector", "salesforce_account", "salesforce-guarded-write-events.v1"),
  read("app.projects.list", "read", "projects"),
  read("app.projects.show", "read", "project"),
  mutation("app.projects.create", "run.agent", "project", "projects.atomic-events.v1"),
  mutation("app.projects.update", "run.agent", "project", "projects.atomic-events.v1"),
  mutation("app.projects.plan", "run.agent", "project_plan", "projects.atomic-events.v1"),
  mutation("app.projects.execution.control", "manage.workflow", "project_execution", "projects.atomic-events.v1"),
  mutation("app.projects.artifacts.feedback", "run.agent", "project_artifact", "projects.atomic-events.v1"),
  read("app.projects.builder.show", "read", "app_builder_session"),
  mutation("app.projects.builder.create", "run.agent", "app_builder_session", "app-builder-events.v1"),
  read("app.projects.builder.tree", "read", "app_builder_file_tree"),
  read("app.projects.builder.file.read", "read", "app_builder_file"),
  mutation("app.projects.builder.file.update", "run.agent", "app_builder_file", "app-builder-events.v1"),
  mutation("app.projects.builder.command.run", "run.agent", "app_builder_command", "app-builder-events.v1"),
  mutation("app.projects.builder.checkpoint.create", "run.agent", "app_builder_checkpoint", "app-builder-events.v1"),
  mutation("app.projects.builder.checkpoint.restore", "run.agent", "app_builder_checkpoint", "app-builder-events.v1"),
  read("app.projects.builder.verification.show", "read", "app_builder_verification"),
  mutation("app.projects.builder.verification.run", "run.agent", "app_builder_verification", "app-builder-events.v1"),
  mutation("app.projects.builder.sentinel.record", "run.agent", "app_builder_verification", "app-builder-events.v1"),
  read("app.projects.builder.repositories.list", "read", "app_builder_repository"),
  mutation("app.projects.builder.repository.bind", "run.agent", "app_builder_repository", "app-builder-events.v1"),
  mutation("app.projects.builder.delivery.create", "run.agent", "app_builder_delivery", "app-builder-events.v1"),
  mutation("app.projects.builder.stop", "run.agent", "app_builder_session", "app-builder-events.v1"),
  mutation("app.work_items.create", "run.agent", "project_task", "projects.atomic-events.v1"),
  mutation("app.work_items.update", "run.agent", "project_task", "projects.atomic-events.v1"),
  read("app.knowledge.delete.preview", "write.memory", "knowledge"),
  mutation("app.knowledge.delete", "write.memory", "knowledge", "memory.atomic-events.v1"),
  read("app.today.show", "read", "today"),
  read("app.today.agenda.show", "read", "today_agenda"),
  mutation("app.today.item.create", "run.agent", "today_item", "tool-execution-events.v1"),
  mutation("app.today.item.update", "run.agent", "today_item", "tool-execution-events.v1"),
  read("app.today.brief.show", "read", "daily_brief"),
  mutation("app.today.brief.generate", "run.agent", "daily_brief", "tool-execution-events.v1"),
  mutation("app.today.preferences.update", "run.agent", "daily_brief_preferences", "tool-execution-events.v1"),
  read("app.notifications.list", "read", "personal_notifications"),
  mutation("app.notifications.update", "run.agent", "personal_notification", "notifications.atomic-events.v1"),
  mutation("app.notifications.read_all", "run.agent", "personal_notifications", "notifications.atomic-events.v1"),
  read("app.runs.show", "read", "agent_run"),
  read("app.runs.activity", "read", "agent_run_activity"),
  read("app.runs.trajectory", "read", "run_trajectory"),
  read("app.conversations.canvas.show", "read", "conversation_canvas"),
  read("app.agents.list", "read", "custom_agent"),
  read("app.agents.show", "read", "custom_agent"),
  read("app.agents.cards", "read", "agent_card"),
  read("app.agents.performance", "read", "agent_performance"),
  read("app.agents.council.show", "read", "agent_council"),
  mutation("app.agents.create", "manage.workflow", "custom_agent", "agent-identity-events.v1"),
  mutation("app.agents.update", "manage.workflow", "custom_agent", "agent-identity-events.v1"),
  read("app.agents.delete.preview", "manage.workflow", "custom_agent"),
  mutation("app.agents.delete", "manage.workflow", "custom_agent", "trash-lifecycle-events.v1"),
  read("app.agents.release.show", "read", "agent_release"),
  mutation("app.agents.release.evaluate", "manage.workflow", "agent_release", "agent-release-events.v1"),
  mutation("app.agents.release.transition", "manage.workflow", "agent_release", "agent-release-events.v1"),
  read("app.agents.release.retire.preview", "manage.workflow", "agent_release"),
  mutation("app.agents.release.retire", "manage.workflow", "agent_release", "agent-release-events.v1"),
  read("app.agents.grants.list", "read", "agent_memory_grant"),
  mutation("app.agents.grants.create", "manage.workflow", "agent_memory_grant", "memory-grant-events.v1"),
  read("app.agents.grants.revoke.preview", "manage.workflow", "agent_memory_grant"),
  mutation("app.agents.grants.revoke", "manage.workflow", "agent_memory_grant", "memory-grant-events.v1"),
  read("app.agents.adaptations.list", "read", "agent_adaptation"),
  mutation("app.agents.adaptations.refresh", "manage.workflow", "agent_adaptation", "agent-adaptation-events.v1"),
  mutation("app.agents.adaptations.manage", "manage.workflow", "agent_adaptation", "agent-adaptation-events.v1"),
  read("app.skills.list", "read", "agent_skill"),
  read("app.skills.show", "read", "agent_skill"),
  mutation("app.skills.create", "manage.workflow", "agent_skill", "tool-execution-events.v1"),
  mutation("app.skills.update", "manage.workflow", "agent_skill", "tool-execution-events.v1"),
  read("app.skills.delete.preview", "manage.workflow", "agent_skill"),
  mutation("app.skills.delete", "manage.workflow", "agent_skill", "trash-lifecycle-events.v1"),
  read("app.workflows.list", "read", "workflow"),
  read("app.workflows.show", "read", "workflow"),
  read("app.workflows.trajectory", "read", "workflow_trajectory"),
  read("app.workflows.plans.list", "read", "workflow_plan"),
  mutation("app.workflows.plan", "manage.workflow", "workflow_plan", "workflow-events.v1"),
  read("app.workflows.executions.list", "read", "workflow_plan_execution"),
  mutation("app.workflows.start", "manage.workflow", "workflow", "workflow-events.v1"),
  mutation("app.workflows.signal", "manage.workflow", "workflow", "workflow-events.v1"),
  mutation("app.workflows.tick", "manage.workflow", "workflow", "workflow-events.v1"),
  read("app.connectors.list", "read", "connector"),
  read("app.connectors.show", "read", "connector"),
  mutation("app.connectors.register", "manage.connector", "connector", "connector-events.v1"),
  mutation("app.connectors.update", "manage.connector", "connector", "connector-events.v1"),
  mutation("app.connectors.refresh", "manage.connector", "connector", "connector-events.v1"),
  mutation("app.connectors.review", "manage.connector", "connector_contract", "connector-events.v1"),
  read("app.connectors.delete.preview", "manage.connector", "connector"),
  mutation("app.connectors.delete", "manage.connector", "connector", "trash-lifecycle-events.v1"),
  read("app.trash.list", "read", "trash_item"),
  read("app.trash.show", "read", "trash_item"),
  read("app.trash.receipts.list", "read", "trash_effect_receipt"),
  read("app.trash.restore.preview", "read", "trash_item"),
  mutation("app.trash.restore", "manage.workflow", "trash_item", "trash-lifecycle-events.v1"),
  read("app.trash.purge.preview", "read", "trash_item"),
  mutation("app.trash.purge", "manage.workflow", "trash_item", "trash-lifecycle-events.v1"),
  read("app.settings.show", "read", "settings"),
  read("app.settings.models.list", "read", "model_catalog"),
  mutation("app.settings.assignments.update", "manage.connector", "model_assignment", "settings-events.v1"),
  mutation("app.settings.mcp.update", "manage.connector", "mcp_export", "settings-events.v1"),
  mutation("app.settings.providers.update", "manage.connector", "provider_connection", "settings-events.v1"),
  mutation("app.settings.providers.validate", "manage.connector", "provider_connection", "settings-events.v1"),
  read("app.settings.providers.revoke.preview", "manage.connector", "provider_connection"),
  mutation("app.settings.providers.revoke", "manage.connector", "provider_connection", "settings-events.v1"),
  read("app.settings.api_keys.list", "read", "service_api_key"),
  read("app.settings.api_keys.revoke.preview", "manage.connector", "service_api_key"),
  mutation("app.settings.api_keys.revoke", "manage.connector", "service_api_key", "settings-events.v1"),
  read("app.communications.policies.list", "read", "person_contact_policy"),
  mutation("app.communications.policies.upsert", "manage.workflow", "person_contact_policy", "governed-communication-events.v1"),
  read("app.communications.drafts.list", "read", "message_draft"),
  mutation("app.communications.drafts.create", "run.agent", "message_draft", "governed-communication-events.v1"),
  mutation("app.communications.deliver", "run.agent", "delivery_receipt", "governed-communication-events.v1"),
  read("app.payments.ap2.readiness", "read", "ap2_readiness"),
  read("app.payments.ap2.transactions.list", "read", "ap2_payment_transaction"),
  read("app.payments.ap2.transactions.show", "read", "ap2_payment_transaction"),
  read("app.payments.ap2.mandates.list", "read", "ap2_mandate_review"),
  mutation("app.payments.ap2.mandates.prepare", "run.agent", "ap2_mandate_review", "ap2-human-present-events.v1"),
  read("app.assets.list", "read", "capture_asset"),
  read("app.assets.show", "read", "capture_asset"),
  mutation("app.assets.index", "write.memory", "capture_asset", "capture-events.v1"),
  mutation("app.assets.recordings.start", "write.memory", "capture_recording", "capture-events.v1"),
  mutation("app.assets.recordings.update", "write.memory", "capture_recording", "capture-events.v1"),
  mutation("app.assets.recordings.complete", "write.memory", "capture_recording", "capture-events.v1"),
  read("app.assets.delete.preview", "write.memory", "capture_asset"),
  mutation("app.assets.delete", "write.memory", "capture_asset", "capture-events.v1"),
  mutation("app.runs.feedback", "run.agent", "agent_run_feedback", "run-events.v1"),
  mutation("app.runs.cancel", "run.agent", "agent_run", "run-events.v1"),
  read("missions.list", "read", "missions"),
  read("missions.show", "read", "mission"),
  mutation("missions.create", "run.agent", "mission", "missions.atomic-events.v1"),
  mutation("missions.transition", "run.agent", "mission", "missions.atomic-events.v1"),
  mutation("mission.task.create", "manage.workflow", "mission_task", "missions.atomic-events.v1"),
  mutation("mission.task.comment", "manage.workflow", "mission_task_comment", "missions.atomic-events.v1"),
  mutation("mission.task.start", "manage.workflow", "mission_task", "governed-workflow-events.v1"),
  read("runs.list", "read", "agent_run"),
  read("memory.list", "read", "memory"),
  read("memory.search", "read", "memory"),
  read("memory.inspect", "read", "memory"),
  read("memory.forget.preview", "write.memory", "memory"),
  read("memory.export", "read", "memory"),
  mutation("memory.write", "write.memory", "memory", "memory.atomic-events.v1"),
  mutation("memory.correct", "write.memory", "memory", "memory.atomic-events.v1"),
  mutation("memory.lifecycle", "write.memory", "memory", "memory.atomic-events.v1"),
  mutation("memory.forget", "write.memory", "memory", "memory.atomic-events.v1"),
  read("knowledge.list", "read", "knowledge"),
  read("knowledge.search", "read", "knowledge"),
  mutation("knowledge.ingest", "write.memory", "knowledge", "memory.atomic-events.v1"),
  mutation("knowledge.delete_source", "write.memory", "knowledge", "memory.atomic-events.v1"),
] satisfies readonly AppServiceOperationContract[]);

export type AppServiceOperation =
  (typeof APP_SERVICE_OPERATION_CONTRACTS)[number]["operation"];

export const MAIN_AGENT_APP_SERVICE_BINDINGS = Object.freeze([
  { toolId: "app.workspaces.summary", operation: "app.workspaces.summary" },
  { toolId: "app.workspaces.readiness", operation: "app.workspaces.readiness" },
  { toolId: "app.integrations.overview.show", operation: "app.integrations.overview.show" },
  { toolId: "app.sources.coverage.show", operation: "app.sources.coverage.show" },
  { toolId: "app.market_research.overview.show", operation: "app.market_research.overview.show" },
  { toolId: "app.market_research.bars.list", operation: "app.market_research.bars.list" },
  { toolId: "app.market_research.features.show", operation: "app.market_research.features.show" },
  { toolId: "app.market_research.analysis.list", operation: "app.market_research.analysis.list" },
  { toolId: "app.market_research.analysis.generate", operation: "app.market_research.analysis.generate" },
  { toolId: "app.market_research.baselines.show", operation: "app.market_research.baselines.show" },
  { toolId: "app.market_research.journal.list", operation: "app.market_research.journal.list" },
  { toolId: "app.market_research.journal.generate", operation: "app.market_research.journal.generate" },
  { toolId: "app.market_research.journal.score", operation: "app.market_research.journal.score" },
  { toolId: "app.memory.shared.list", operation: "app.memory.shared.list" },
  { toolId: "app.memory.shared.write", operation: "app.memory.shared.write" },
  { toolId: "app.workspace_templates.list", operation: "app.workspace_templates.list" },
  { toolId: "app.workspace_templates.publish", operation: "app.workspace_templates.publish" },
  { toolId: "app.workspace_templates.instantiate", operation: "app.workspace_templates.instantiate" },
  { toolId: "app.meetings.list", operation: "app.meetings.list" },
  { toolId: "app.meetings.show", operation: "app.meetings.show" },
  { toolId: "app.meetings.create", operation: "app.meetings.create" },
  { toolId: "app.meetings.update", operation: "app.meetings.update" },
  { toolId: "app.meetings.commitments.list", operation: "app.meetings.commitments.list" },
  { toolId: "app.meetings.commitments.propose", operation: "app.meetings.commitments.propose" },
  { toolId: "app.meetings.commitments.resolve", operation: "app.meetings.commitments.resolve" },
  { toolId: "app.customer_accounts.list", operation: "app.customer_accounts.list" },
  { toolId: "app.customer_accounts.show", operation: "app.customer_accounts.show" },
  { toolId: "app.customer_accounts.portfolio.show", operation: "app.customer_accounts.portfolio.show" },
  { toolId: "app.customer_accounts.intelligence.show", operation: "app.customer_accounts.intelligence.show" },
  { toolId: "app.customer_accounts.create", operation: "app.customer_accounts.create" },
  { toolId: "app.customer_accounts.revise", operation: "app.customer_accounts.revise" },
  { toolId: "app.customer_accounts.facts.record", operation: "app.customer_accounts.facts.record" },
  { toolId: "app.customer_accounts.health.show", operation: "app.customer_accounts.health.show" },
  { toolId: "app.customer_accounts.health.evaluate", operation: "app.customer_accounts.health.evaluate" },
  { toolId: "app.customer_accounts.workflows.list", operation: "app.customer_accounts.workflows.list" },
  { toolId: "app.customer_accounts.workflows.start", operation: "app.customer_accounts.workflows.start" },
  { toolId: "app.customer_accounts.workflows.outcome.record", operation: "app.customer_accounts.workflows.outcome.record" },
  { toolId: "app.customer_accounts.salesforce.writes.configure", operation: "app.customer_accounts.salesforce.writes.configure" },
  { toolId: "app.customer_accounts.salesforce.contact.create", operation: "app.customer_accounts.salesforce.contact.create" },
  { toolId: "app.customer_accounts.salesforce.contact.update", operation: "app.customer_accounts.salesforce.contact.update" },
  { toolId: "app.customer_accounts.salesforce.task.create", operation: "app.customer_accounts.salesforce.task.create" },
  { toolId: "app.customer_accounts.salesforce.task.update", operation: "app.customer_accounts.salesforce.task.update" },
  { toolId: "app.customer_accounts.salesforce.note.update", operation: "app.customer_accounts.salesforce.note.update" },
  { toolId: "app.customer_accounts.salesforce.case.create", operation: "app.customer_accounts.salesforce.case.create" },
  { toolId: "app.customer_accounts.salesforce.case.update", operation: "app.customer_accounts.salesforce.case.update" },
  { toolId: "app.customer_accounts.salesforce.opportunity.create", operation: "app.customer_accounts.salesforce.opportunity.create" },
  { toolId: "app.customer_accounts.salesforce.opportunity.update", operation: "app.customer_accounts.salesforce.opportunity.update" },
  { toolId: "app.customer_accounts.salesforce.account.update", operation: "app.customer_accounts.salesforce.account.update" },
  { toolId: "app.projects.list", operation: "app.projects.list" },
  { toolId: "app.projects.show", operation: "app.projects.show" },
  { toolId: "app.projects.create", operation: "app.projects.create" },
  { toolId: "app.projects.update", operation: "app.projects.update" },
  { toolId: "app.projects.plan", operation: "app.projects.plan" },
  { toolId: "app.projects.execution.control", operation: "app.projects.execution.control" },
  { toolId: "app.projects.artifacts.feedback", operation: "app.projects.artifacts.feedback" },
  { toolId: "app.projects.builder.show", operation: "app.projects.builder.show" },
  { toolId: "app.projects.builder.create", operation: "app.projects.builder.create" },
  { toolId: "app.projects.builder.tree", operation: "app.projects.builder.tree" },
  { toolId: "app.projects.builder.file.read", operation: "app.projects.builder.file.read" },
  { toolId: "app.projects.builder.file.update", operation: "app.projects.builder.file.update" },
  { toolId: "app.projects.builder.command.run", operation: "app.projects.builder.command.run" },
  { toolId: "app.projects.builder.checkpoint.create", operation: "app.projects.builder.checkpoint.create" },
  { toolId: "app.projects.builder.checkpoint.restore", operation: "app.projects.builder.checkpoint.restore" },
  { toolId: "app.projects.builder.verification.show", operation: "app.projects.builder.verification.show" },
  { toolId: "app.projects.builder.verification.run", operation: "app.projects.builder.verification.run" },
  { toolId: "app.projects.builder.sentinel.record", operation: "app.projects.builder.sentinel.record" },
  { toolId: "app.projects.builder.repositories.list", operation: "app.projects.builder.repositories.list" },
  { toolId: "app.projects.builder.repository.bind", operation: "app.projects.builder.repository.bind" },
  { toolId: "app.projects.builder.delivery.create", operation: "app.projects.builder.delivery.create" },
  { toolId: "app.projects.builder.stop", operation: "app.projects.builder.stop" },
  { toolId: "app.work_items.create", operation: "app.work_items.create" },
  { toolId: "app.work_items.update", operation: "app.work_items.update" },
  { toolId: "app.memory.readable.show", operation: "app.memory.readable.show" },
  { toolId: "app.memory.intelligence.show", operation: "app.memory.intelligence.show" },
  { toolId: "app.memory.list", operation: "memory.list" },
  { toolId: "app.memory.search", operation: "memory.search" },
  { toolId: "app.memory.inspect", operation: "memory.inspect" },
  { toolId: "app.memory.write", operation: "memory.write" },
  { toolId: "app.memory.correct", operation: "memory.correct" },
  { toolId: "app.memory.lifecycle", operation: "memory.lifecycle" },
  { toolId: "app.memory.forget.preview", operation: "memory.forget.preview" },
  { toolId: "app.memory.forget", operation: "memory.forget" },
  { toolId: "app.memory.export", operation: "memory.export" },
  { toolId: "app.knowledge.list", operation: "knowledge.list" },
  { toolId: "app.knowledge.search", operation: "knowledge.search" },
  { toolId: "app.knowledge.ingest", operation: "knowledge.ingest" },
  { toolId: "app.knowledge.delete.preview", operation: "app.knowledge.delete.preview" },
  { toolId: "app.knowledge.delete", operation: "app.knowledge.delete" },
  { toolId: "app.today.show", operation: "app.today.show" },
  { toolId: "app.today.agenda.show", operation: "app.today.agenda.show" },
  { toolId: "app.today.item.create", operation: "app.today.item.create" },
  { toolId: "app.today.item.update", operation: "app.today.item.update" },
  { toolId: "app.today.brief.show", operation: "app.today.brief.show" },
  { toolId: "app.today.brief.generate", operation: "app.today.brief.generate" },
  { toolId: "app.today.preferences.update", operation: "app.today.preferences.update" },
  { toolId: "app.notifications.list", operation: "app.notifications.list" },
  { toolId: "app.notifications.update", operation: "app.notifications.update" },
  { toolId: "app.notifications.read_all", operation: "app.notifications.read_all" },
  { toolId: "app.runs.list", operation: "runs.list" },
  { toolId: "app.runs.show", operation: "app.runs.show" },
  { toolId: "app.runs.activity", operation: "app.runs.activity" },
  { toolId: "app.runs.trajectory", operation: "app.runs.trajectory" },
  { toolId: "app.agents.list", operation: "app.agents.list" },
  { toolId: "app.agents.show", operation: "app.agents.show" },
  { toolId: "app.agents.cards", operation: "app.agents.cards" },
  { toolId: "app.agents.performance", operation: "app.agents.performance" },
  { toolId: "app.agents.council.show", operation: "app.agents.council.show" },
  { toolId: "app.agents.create", operation: "app.agents.create" },
  { toolId: "app.agents.update", operation: "app.agents.update" },
  { toolId: "app.agents.delete.preview", operation: "app.agents.delete.preview" },
  { toolId: "app.agents.delete", operation: "app.agents.delete" },
  { toolId: "app.agents.release.show", operation: "app.agents.release.show" },
  { toolId: "app.agents.release.evaluate", operation: "app.agents.release.evaluate" },
  { toolId: "app.agents.release.transition", operation: "app.agents.release.transition" },
  { toolId: "app.agents.release.retire.preview", operation: "app.agents.release.retire.preview" },
  { toolId: "app.agents.release.retire", operation: "app.agents.release.retire" },
  { toolId: "app.agents.grants.list", operation: "app.agents.grants.list" },
  { toolId: "app.agents.grants.create", operation: "app.agents.grants.create" },
  { toolId: "app.agents.grants.revoke.preview", operation: "app.agents.grants.revoke.preview" },
  { toolId: "app.agents.grants.revoke", operation: "app.agents.grants.revoke" },
  { toolId: "app.agents.adaptations.list", operation: "app.agents.adaptations.list" },
  { toolId: "app.agents.adaptations.refresh", operation: "app.agents.adaptations.refresh" },
  { toolId: "app.agents.adaptations.manage", operation: "app.agents.adaptations.manage" },
  { toolId: "app.skills.list", operation: "app.skills.list" },
  { toolId: "app.skills.show", operation: "app.skills.show" },
  { toolId: "app.skills.create", operation: "app.skills.create" },
  { toolId: "app.skills.update", operation: "app.skills.update" },
  { toolId: "app.skills.delete.preview", operation: "app.skills.delete.preview" },
  { toolId: "app.skills.delete", operation: "app.skills.delete" },
  { toolId: "app.workflows.list", operation: "app.workflows.list" },
  { toolId: "app.workflows.show", operation: "app.workflows.show" },
  { toolId: "app.workflows.trajectory", operation: "app.workflows.trajectory" },
  { toolId: "app.workflows.plans.list", operation: "app.workflows.plans.list" },
  { toolId: "app.workflows.plan", operation: "app.workflows.plan" },
  { toolId: "app.workflows.executions.list", operation: "app.workflows.executions.list" },
  { toolId: "app.workflows.start", operation: "app.workflows.start" },
  { toolId: "app.workflows.signal", operation: "app.workflows.signal" },
  { toolId: "app.workflows.tick", operation: "app.workflows.tick" },
  { toolId: "app.connectors.list", operation: "app.connectors.list" },
  { toolId: "app.connectors.show", operation: "app.connectors.show" },
  { toolId: "app.connectors.register", operation: "app.connectors.register" },
  { toolId: "app.connectors.update", operation: "app.connectors.update" },
  { toolId: "app.connectors.refresh", operation: "app.connectors.refresh" },
  { toolId: "app.connectors.review", operation: "app.connectors.review" },
  { toolId: "app.connectors.delete.preview", operation: "app.connectors.delete.preview" },
  { toolId: "app.connectors.delete", operation: "app.connectors.delete" },
  { toolId: "app.trash.list", operation: "app.trash.list" },
  { toolId: "app.trash.show", operation: "app.trash.show" },
  { toolId: "app.trash.receipts.list", operation: "app.trash.receipts.list" },
  { toolId: "app.trash.restore.preview", operation: "app.trash.restore.preview" },
  { toolId: "app.trash.restore", operation: "app.trash.restore" },
  { toolId: "app.trash.purge.preview", operation: "app.trash.purge.preview" },
  { toolId: "app.trash.purge", operation: "app.trash.purge" },
  { toolId: "app.settings.show", operation: "app.settings.show" },
  { toolId: "app.settings.models.list", operation: "app.settings.models.list" },
  { toolId: "app.settings.assignments.update", operation: "app.settings.assignments.update" },
  { toolId: "app.settings.mcp.update", operation: "app.settings.mcp.update" },
  { toolId: "app.settings.providers.update", operation: "app.settings.providers.update" },
  { toolId: "app.settings.providers.validate", operation: "app.settings.providers.validate" },
  { toolId: "app.settings.providers.revoke.preview", operation: "app.settings.providers.revoke.preview" },
  { toolId: "app.settings.providers.revoke", operation: "app.settings.providers.revoke" },
  { toolId: "app.settings.api_keys.list", operation: "app.settings.api_keys.list" },
  { toolId: "app.settings.api_keys.revoke.preview", operation: "app.settings.api_keys.revoke.preview" },
  { toolId: "app.settings.api_keys.revoke", operation: "app.settings.api_keys.revoke" },
  { toolId: "app.communications.policies.list", operation: "app.communications.policies.list" },
  { toolId: "app.communications.policies.upsert", operation: "app.communications.policies.upsert" },
  { toolId: "app.communications.drafts.list", operation: "app.communications.drafts.list" },
  { toolId: "app.communications.drafts.create", operation: "app.communications.drafts.create" },
  { toolId: "app.communications.deliver", operation: "app.communications.deliver" },
  { toolId: "app.payments.ap2.readiness", operation: "app.payments.ap2.readiness" },
  { toolId: "app.payments.ap2.transactions.list", operation: "app.payments.ap2.transactions.list" },
  { toolId: "app.payments.ap2.transactions.show", operation: "app.payments.ap2.transactions.show" },
  { toolId: "app.payments.ap2.mandates.list", operation: "app.payments.ap2.mandates.list" },
  { toolId: "app.payments.ap2.mandates.prepare", operation: "app.payments.ap2.mandates.prepare" },
  { toolId: "app.assets.list", operation: "app.assets.list" },
  { toolId: "app.assets.show", operation: "app.assets.show" },
  { toolId: "app.assets.index", operation: "app.assets.index" },
  { toolId: "app.assets.recordings.start", operation: "app.assets.recordings.start" },
  { toolId: "app.assets.recordings.update", operation: "app.assets.recordings.update" },
  { toolId: "app.assets.recordings.complete", operation: "app.assets.recordings.complete" },
  { toolId: "app.assets.delete.preview", operation: "app.assets.delete.preview" },
  { toolId: "app.assets.delete", operation: "app.assets.delete" },
  { toolId: "app.runs.feedback", operation: "app.runs.feedback" },
  { toolId: "app.runs.cancel", operation: "app.runs.cancel" },
  { toolId: "memory.search", operation: "memory.search" },
  { toolId: "memory.inspect", operation: "memory.inspect" },
  { toolId: "memory.forget.preview", operation: "memory.forget.preview" },
  { toolId: "memory.write", operation: "memory.write" },
  { toolId: "memory.correct", operation: "memory.correct" },
  { toolId: "memory.lifecycle", operation: "memory.lifecycle" },
  { toolId: "memory.forget", operation: "memory.forget" },
  { toolId: "memory.export", operation: "memory.export" },
  { toolId: "knowledge.search", operation: "knowledge.search" },
  { toolId: "knowledge.ingest", operation: "knowledge.ingest" },
  { toolId: "missions.list", operation: "missions.list" },
  { toolId: "mission.show", operation: "missions.show" },
  { toolId: "mission.task.create", operation: "mission.task.create" },
  { toolId: "mission.task.comment", operation: "mission.task.comment" },
  { toolId: "runs.list", operation: "runs.list" },
] satisfies ReadonlyArray<{
  toolId: string;
  operation: AppServiceOperation;
}>);

export const MAIN_AGENT_EXCLUDED_APP_OPERATIONS = Object.freeze([
  { operation: "app.connectors.credentials.write", reason: "Raw connector credentials must use the human-only secret entry surface." },
  { operation: "app.settings.providers.create", reason: "Provider credentials must use the human-only secret entry surface." },
  { operation: "app.settings.providers.rotate", reason: "Provider credentials must use the human-only secret rotation surface." },
  { operation: "app.settings.api_keys.create", reason: "One-time bearer tokens must never enter an agent transcript or tool ledger." },
  { operation: "app.assets.upload", reason: "Raw binary uploads must use the direct user-to-storage capture surface." },
  { operation: "app.assets.recordings.segment.write", reason: "Raw recording audio must use the direct user-to-storage capture surface." },
  { operation: "app.runs.activity.frame.read", reason: "Raw browser frame and accessibility-snapshot bytes use authenticated owner-scoped delivery surfaces and must not be copied into tool transcripts." },
  { operation: "app.runs.fork", reason: "Checkpoint correction forks launch a new Main Agent execution and remain an explicit user action to prevent recursive self-forking." },
] as const);

const byOperation = new Map(
  APP_SERVICE_OPERATION_CONTRACTS.map((contract) => [contract.operation, contract]),
);

export function getAppServiceOperationContract(
  operation: AppServiceOperation,
): AppServiceOperationContract {
  const contract = byOperation.get(operation);
  if (!contract) {
    throw new Error(`Application service operation ${operation} is not registered.`);
  }
  return contract;
}

export function validateAppServiceRegistry() {
  const operations = APP_SERVICE_OPERATION_CONTRACTS.map((entry) => entry.operation);
  const duplicateOperations = operations.filter(
    (operation, index) => operations.indexOf(operation) !== index,
  );
  const mutationContracts = APP_SERVICE_OPERATION_CONTRACTS.filter(
    (entry) => entry.accessMode === "mutation",
  );
  const invalidMutationContracts = mutationContracts
    .filter((entry) => entry.eventContract === readOnlyEventContract)
    .map((entry) => entry.operation);
  const missingAgentOperations = MAIN_AGENT_APP_SERVICE_BINDINGS
    .filter((binding) => !byOperation.has(binding.operation))
    .map((binding) => binding.toolId);
  return {
    version: APP_SERVICE_REGISTRY_VERSION,
    operationCount: operations.length,
    mutationCount: mutationContracts.length,
    duplicateOperations: [...new Set(duplicateOperations)],
    invalidMutationContracts,
    mainAgentOperationCount: MAIN_AGENT_APP_SERVICE_BINDINGS.length,
    excludedAgentOperationCount: MAIN_AGENT_EXCLUDED_APP_OPERATIONS.length,
    missingAgentOperations,
    agentAccessPaths: ["governed_tool_executor", "application_service"] as const,
    forbiddenAgentAccessPaths: [] as readonly string[],
    registrySha256: canonicalJsonSha256(APP_SERVICE_OPERATION_CONTRACTS),
    passed:
      duplicateOperations.length === 0 &&
      invalidMutationContracts.length === 0 &&
      missingAgentOperations.length === 0,
  };
}

function read<const TOperation extends string>(
  operation: TOperation,
  action: string,
  resourceType: string,
): AppServiceOperationContract & { operation: TOperation } {
  return Object.freeze({
    operation,
    action,
    resourceType,
    accessMode: "read",
    eventContract: readOnlyEventContract,
  });
}

function mutation<const TOperation extends string>(
  operation: TOperation,
  action: string,
  resourceType: string,
  eventContract: string,
): AppServiceOperationContract & { operation: TOperation } {
  return Object.freeze({
    operation,
    action,
    resourceType,
    accessMode: "mutation",
    eventContract,
  });
}
